import type { ColorScheme } from "../../color-schemes";

export const COLOR_SCHEMES: ColorScheme[] = [
  {
    id: "nourivelle-sea-glass",
    name: "Sea Glass",
    category: "light",
    palette: {
      primary: "#426A66",
      secondary: "#73BFA5",
      accent: "#C83458",
      background: "#FFFFFF",
      surface: "#F0F7FA",
      text: "#315654",
      textMuted: "#566F6E",
      border: "#DCE9EA",
    },
    headingFont: "Manrope",
    bodyFont: "DM Sans",
    accentFont: "Playfair Display",
  },
  {
    id: "nourivelle-sage-morning",
    name: "Sage Morning",
    category: "light",
    palette: {
      primary: "#416852",
      secondary: "#85B99B",
      accent: "#B44736",
      background: "#FFFFFF",
      surface: "#F4F8F1",
      text: "#304A3C",
      textMuted: "#596E61",
      border: "#DEE9DE",
    },
    headingFont: "Manrope",
    bodyFont: "DM Sans",
    accentFont: "Playfair Display",
  },
  {
    id: "nourivelle-coastal-air",
    name: "Coastal Air",
    category: "light",
    palette: {
      primary: "#365F68",
      secondary: "#76B7B5",
      accent: "#BD3F5A",
      background: "#FFFFFF",
      surface: "#EFF7F8",
      text: "#2D4D53",
      textMuted: "#536D72",
      border: "#D8E8EA",
    },
    headingFont: "DM Sans",
    bodyFont: "Manrope",
    accentFont: "Cormorant Garamond",
  },
  {
    id: "nourivelle-evening-ritual",
    name: "Evening Ritual",
    category: "dark",
    palette: {
      primary: "#78BCA7",
      secondary: "#3E7770",
      accent: "#F08491",
      background: "#162E2D",
      surface: "#203B39",
      text: "#F2F8F5",
      textMuted: "#B8D0C9",
      border: "#3B5B56",
    },
    headingFont: "Manrope",
    bodyFont: "DM Sans",
    accentFont: "Playfair Display",
  },
];