import type { SectionTypeDefinition } from "../../template-types";
import { ACCENT, BODY, HEADING, IMAGES, inferFields, vid } from "./shared";

const PRODUCT_ITEMS = [
  { name: "Magnesium Malam", category: "Tidur & Relaksasi", price: "Rp 189.000", image: IMAGES.productOne, badge: "Favorit" },
  { name: "Daily Greens", category: "Nutrisi Harian", price: "Rp 229.000", image: IMAGES.productTwo, badge: "Baru" },
  { name: "Barrier Care Serum", category: "Perawatan Kulit", price: "Rp 159.000", image: IMAGES.productThree, badge: "Pilihan" },
  { name: "Recovery Protein", category: "Aktif & Bugar", price: "Rp 279.000", image: IMAGES.productFour, badge: "Terlaris" },
  { name: "Vitamin D3 + K2", category: "Imunitas", price: "Rp 139.000", image: IMAGES.productFive, badge: "Harian" },
];

export const SECTION_CONFIGS: Record<string, Record<string, unknown>> = {
  hero: { badge: "Ritual sehat, terasa lebih dekat", headline: "Rawat dirimu, dengan cara yang terasa baik", subheadline: "Pilihan nutrisi dan perawatan harian untuk mendukung versi terbaik dirimu.", cta_text: "Temukan Ritualmu", cta_link: "#produk", image: IMAGES.hero },
  features: { title: "Lebih Banyak Manfaat, Mulai dari Sini", subtitle: "Belanja terasa lebih tenang dengan perhatian di setiap langkah.", items: [{ icon: "01", title: "Pilihan Terkurasi", description: "Produk wellness dengan informasi yang jelas." }, { icon: "02", title: "Poin Setiap Belanja", description: "Kumpulkan manfaat dari pembelian harian." }, { icon: "03", title: "Dukungan Personal", description: "Tim kami siap membantu sebelum dan sesudah belanja." }, { icon: "04", title: "Gabung Gratis", description: "Nikmati penawaran anggota tanpa biaya langganan." }] },
  product_grid: { title: "Pilihan Baik untuk Harimu", subtitle: "Temukan produk yang pas dengan ritme dan kebutuhanmu.", items: PRODUCT_ITEMS },
  pricing: { title: "Paket Pilihan Minggu Ini", subtitle: "Racikan praktis untuk rutinitas yang lebih seimbang.", items: [{ name: "Daily Balance Set", price: "Rp 329.000", description: "Vitamin harian dan greens untuk memulai pagi." }, { name: "Calm Evening Set", price: "Rp 279.000", description: "Magnesium dan ritual perawatan sebelum tidur." }, { name: "Active Recovery Set", price: "Rp 399.000", description: "Dukungan nutrisi setelah bergerak dan berolahraga." }] },
  testimonials: { title: "Cerita Baik dari Komunitas", subtitle: "Rutinitas kecil yang memberi perubahan berarti.", items: [{ name: "Nadia, Bandung", text: "Pilihan produknya jelas dan timnya membantu saya menemukan rutinitas yang sederhana.", rating: "5.0" }, { name: "Raka, Jakarta", text: "Pengiriman rapi, produknya sesuai deskripsi. Sekarang belanja kebutuhan bulanan lebih praktis.", rating: "4.9" }, { name: "Mira, Surabaya", text: "Suka karena rekomendasinya terasa personal, bukan sekadar mengejar banyak produk.", rating: "5.0" }] },
  gallery: { title: "Temukan Ritme Sehatmu", subtitle: "Inspirasi sederhana untuk tubuh, pikiran, dan keseharian.", images: [{ image: IMAGES.lifestyleOne, caption: "Istirahat berkualitas" }, { image: IMAGES.lifestyleTwo, caption: "Perawatan yang lembut" }, { image: IMAGES.lifestyleThree, caption: "Aktif setiap hari" }, { image: IMAGES.lifestyleFour, caption: "Nutrisi seimbang" }, { image: IMAGES.lifestyleFive, caption: "Waktu untuk diri sendiri" }] },
  location: { title: "Singgah ke Nourivelle", address: "Jl. Cendana No. 18, Bandung", hours: "Senin-Sabtu, 09.00-20.00", note: "Konsultasikan kebutuhanmu atau ambil pesanan langsung di studio kami." },
  faq: { title: "Pertanyaan yang Sering Ditanyakan", items: [{ question: "Bagaimana memilih produk yang sesuai?", answer: "Mulailah dari kebutuhan dan kebiasaanmu. Tim kami bisa membantu menjelaskan informasi produk, namun tidak menggantikan saran tenaga kesehatan." }, { question: "Berapa lama pesanan dikirim?", answer: "Pesanan diproses pada hari kerja. Estimasi pengiriman mengikuti kota tujuan dan pilihan kurir." }, { question: "Apakah produk aman untuk semua orang?", answer: "Periksa komposisi serta petunjuk penggunaan. Jika memiliki kondisi khusus, sedang hamil, atau mengonsumsi obat, konsultasikan dulu dengan tenaga kesehatan." }] },
  contact: { title: "Butuh Bantuan Memilih?", subtitle: "Sampaikan kebutuhanmu. Tim Nourivelle siap membantu dengan informasi produk yang jelas.", phone: "+62 812 3456 7890", email: "halo@nourivelle.id", address: "Bandung, Jawa Barat", cta_text: "Hubungi Tim Kami", cta_link: "#kontak" },
  about: { title: "Pilihan Kecil untuk Merasa Lebih Baik", content: "Nourivelle merangkum nutrisi dan perawatan diri dalam pengalaman belanja yang lebih tenang. Kami percaya setiap rutinitas baik dimulai dari pilihan yang terasa tepat untuk dirimu.", image: IMAGES.wellness, cta_text: "Kenali Kami", cta_link: "#kontak" },
  video: { title: "Kenali Ritual Nourivelle", subtitle: "Cerita tentang bahan, kebiasaan, dan cara merawat diri dengan lebih mindful.", video_url: "https://www.youtube.com/", image: IMAGES.lifestyleTwo },
  team: { title: "Wellness, Sesuai Ritmemu", subtitle: "Jelajahi inspirasi berdasarkan hal yang ingin kamu rawat.", members: [{ name: "Tidur & Relaksasi", role: "Ritual untuk jeda yang berkualitas", image: IMAGES.lifestyleOne }, { name: "Kulit & Kecantikan", role: "Perawatan lembut sehari-hari", image: IMAGES.lifestyleTwo }, { name: "Energi & Gerak", role: "Nutrisi untuk tetap aktif", image: IMAGES.lifestyleThree }, { name: "Nutrisi Seimbang", role: "Pilihan baik untuk rutinitasmu", image: IMAGES.lifestyleFour }] },
  newsletter: { title: "Kabar Baik untuk Rutinitasmu", subtitle: "Dapatkan cerita wellness, pilihan baru, dan penawaran khusus langsung ke inbox.", button_text: "Daftar Sekarang", button_link: "#newsletter" },
  divider: { label: "Ritual baik dimulai dari pilihan kecil" },
  marquee: { items: [{ text: "Pilihan wellness terkurasi" }, { text: "Gratis gabung member" }, { text: "Dukungan personal" }, { text: "Rawat diri setiap hari" }] },
  menu_board: { title: "Jelajahi Kategori", subtitle: "Mulai dari hal yang ingin kamu rawat.", items: [{ name: "Vitamin & Mineral", description: "Dukungan nutrisi untuk rutinitas harian.", count: "24 pilihan", image: IMAGES.productOne }, { name: "Wellness Essentials", description: "Tidur, hidrasi, dan keseimbangan diri.", count: "18 pilihan", image: IMAGES.productTwo }, { name: "Perawatan Kulit", description: "Pilihan lembut untuk ritual kulitmu.", count: "16 pilihan", image: IMAGES.productThree }, { name: "Aktif & Bugar", description: "Teman bergerak dan pemulihan tubuh.", count: "12 pilihan", image: IMAGES.productFour }] },
  steps: { title: "Belanja Jadi Lebih Mudah", subtitle: "Dari menemukan pilihan sampai paket tiba di rumah.", items: [{ number: "01", title: "Jelajahi", description: "Pilih kategori sesuai prioritas wellness-mu." }, { number: "02", title: "Tanyakan", description: "Minta bantuan tim untuk memahami detail produk." }, { number: "03", title: "Nikmati", description: "Pesanan dikemas rapi dan dikirim ke alamatmu." }] },
  cta: { title: "Saatnya Menemukan Pilihanmu", text: "Mulai dari kebutuhan yang paling dekat dengan keseharianmu.", cta_text: "Jelajahi Produk", cta_link: "#produk" },
};

const TYPES = [
  ["hero", "Cerita Utama", "PanelsTopLeft"], ["features", "Manfaat Member", "Sparkles"], ["product_grid", "Katalog Produk", "ShoppingBag"],
  ["pricing", "Paket Pilihan", "BadgePercent"], ["testimonials", "Cerita Pelanggan", "MessageCircle"], ["gallery", "Inspirasi Wellness", "Images"],
  ["location", "Lokasi Studio", "MapPin"], ["faq", "Tanya Jawab", "CircleHelp"], ["contact", "Hubungi Kami", "Phone"],
  ["about", "Cerita Brand", "Heart"], ["video", "Cerita Visual", "Play"], ["team", "Wellness Goals", "Users"],
  ["newsletter", "Kabar Nourivelle", "Mail"], ["divider", "Pemisah Editorial", "Minus"], ["marquee", "Pita Informasi", "MoveHorizontal"],
  ["menu_board", "Jelajah Kategori", "List"], ["steps", "Cara Belanja", "ListOrdered"], ["cta", "Ajakan Belanja", "ArrowRight"],
] as const;

function heading(configTitle = "title", subtitleKey = "subtitle"): string {
  return `<div style="margin-bottom:22px;"><h2 style="${HEADING}font-size:clamp(1.55rem,3vw,2.2rem);line-height:1.15;color:var(--color-text);margin:0;">{{${configTitle}}}</h2><p style="${BODY}font-size:.92rem;line-height:1.6;color:var(--color-text-muted);margin:8px 0 0;">{{${subtitleKey}}}</p></div>`;
}

function itemList(type: string, layout: number): string {
  if (type === "product_grid") {
    const card = `<article style="min-width:${layout === 1 ? "190px" : "0"};flex:${layout === 1 ? "0 0 190px" : "1"};overflow:hidden;border-radius:${layout === 2 ? "18px 18px 6px 6px" : "12px"};background:var(--color-surface);"><div style="position:relative;"><img src="{{image}}" alt="{{name}}" style="display:block;width:100%;max-width:100%;height:auto;aspect-ratio:1/1;object-fit:cover;background:var(--color-background);"/><span style="position:absolute;top:10px;left:10px;display:inline-flex;align-items:center;min-height:26px;padding:0 10px;border-radius:999px;background:var(--color-accent);color:var(--color-on-accent);${BODY}font-size:.68rem;font-weight:700;">{{badge}}</span></div><div style="padding:12px;"><span style="${BODY}font-size:.7rem;color:var(--color-text-muted);">{{category}}</span><h3 style="${HEADING}font-size:.9rem;line-height:1.35;color:var(--color-text);margin:5px 0;">{{name}}</h3><strong style="${BODY}font-size:.88rem;color:var(--color-primary-on-surface);">{{price}}</strong></div></article>`;
    return layout === 1
      ? `<div style="display:flex;gap:12px;overflow-x:auto;padding:2px 2px 12px;scroll-snap-type:x mandatory;">{{#items}}<div style="scroll-snap-align:start;">${card}</div>{{/items}}</div>`
      : `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,155px),1fr));gap:${layout === 2 ? "10px" : "14px"};">{{#items}}${card}{{/items}}</div>`;
  }
  if (type === "features" || type === "steps") {
    const number = type === "steps" ? "{{number}}" : "{{icon}}";
    const title = type === "steps" ? "{{title}}" : "{{title}}";
    const description = type === "steps" ? "{{description}}" : "{{description}}";
    if (layout === 1) return `<div style="display:grid;gap:0;border-top:1px solid var(--color-border);">{{#items}}<article style="display:grid;grid-template-columns:54px minmax(0,1fr);gap:12px;padding:17px 0;border-bottom:1px solid var(--color-border);"><span style="${ACCENT}font-size:1.35rem;color:var(--color-primary-on-background);">${number}</span><div><h3 style="${HEADING}font-size:1rem;color:var(--color-text);margin:0;">${title}</h3><p style="${BODY}font-size:.86rem;line-height:1.55;color:var(--color-text-muted);margin:5px 0 0;">${description}</p></div></article>{{/items}}</div>`;
    return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,200px),1fr));gap:14px;">{{#items}}<article style="padding:${layout === 2 ? "22px 16px" : "18px"};border-radius:${layout === 2 ? "50% 50% 14px 14px" : "12px"};background:${layout === 2 ? "var(--color-primary)" : "var(--color-surface)"};color:${layout === 2 ? "var(--color-on-primary)" : "var(--color-text)"};"><span style="${ACCENT}font-size:1.35rem;color:${layout === 2 ? "var(--color-accent-on-primary)" : "var(--color-primary-on-surface)"};">${number}</span><h3 style="${HEADING}font-size:1rem;margin:9px 0 5px;">${title}</h3><p style="${BODY}font-size:.84rem;line-height:1.55;margin:0;opacity:.9;">${description}</p></article>{{/items}}</div>`;
  }
  if (type === "menu_board") {
    if (layout === 0) return `<div style="display:flex;gap:10px;overflow-x:auto;padding:2px 2px 10px;scroll-snap-type:x mandatory;">{{#items}}<article style="flex:0 0 112px;min-width:0;scroll-snap-align:start;text-align:center;padding:10px 8px;border-radius:12px;background:var(--color-surface);"><img src="{{image}}" alt="" style="display:block;width:44px;height:44px;max-width:100%;margin:0 auto 7px;border-radius:50%;object-fit:cover;"/><h3 style="${HEADING}font-size:.74rem;line-height:1.3;color:var(--color-text);margin:0;">{{name}}</h3><span style="${BODY}font-size:.66rem;color:var(--color-text-muted);">{{count}}</span></article>{{/items}}</div>`;
    if (layout === 1) return `<div style="display:flex;gap:12px;overflow-x:auto;padding-bottom:8px;">{{#items}}<article style="position:relative;flex:0 0 190px;min-width:0;overflow:hidden;border-radius:16px;background:var(--color-surface);"><img src="{{image}}" alt="{{name}}" style="display:block;width:100%;height:auto;aspect-ratio:4/3;object-fit:cover;"/><div style="padding:13px;"><h3 style="${HEADING}font-size:.95rem;color:var(--color-text);margin:0;">{{name}}</h3><span style="${BODY}font-size:.74rem;color:var(--color-primary-on-surface);">{{count}}</span></div></article>{{/items}}</div>`;
    return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,230px),1fr));gap:12px;">{{#items}}<article style="display:flex;align-items:center;gap:14px;padding:14px;border-radius:${layout === 2 ? "999px" : "12px"};background:var(--color-surface);"><img src="{{image}}" alt="" style="width:72px;height:72px;max-width:100%;border-radius:50%;object-fit:cover;flex:none;"/><div><h3 style="${HEADING}font-size:.92rem;color:var(--color-text);margin:0;">{{name}}</h3><p style="${BODY}font-size:.78rem;line-height:1.45;color:var(--color-text-muted);margin:4px 0;">{{description}}</p><span style="${BODY}font-size:.72rem;color:var(--color-primary-on-surface);">{{count}}</span></div></article>{{/items}}</div>`;
  }
  if (type === "testimonials" || type === "faq" || type === "pricing") {
    if (type === "faq") return `<div style="display:grid;gap:10px;">{{#items}}<details style="padding:16px 18px;border-radius:${layout === 2 ? "0 14px 14px 0" : "12px"};border:${layout === 1 ? "0" : "1px solid var(--color-border)"};border-left:${layout === 2 ? "4px solid var(--color-secondary)" : "1px solid var(--color-border)"};background:var(--color-surface);"><summary style="${BODY}font-size:.92rem;font-weight:700;color:var(--color-text);cursor:pointer;">{{question}}</summary><p style="${BODY}font-size:.86rem;line-height:1.65;color:var(--color-text-muted);margin:10px 0 0;">{{answer}}</p></details>{{/items}}</div>`;
    const itemContent = type === "pricing"
      ? `<span style="${BODY}font-size:.74rem;color:var(--color-text-muted);">PILIHAN NOURIVELLE</span><h3 style="${HEADING}font-size:1.03rem;color:var(--color-text);margin:8px 0;">{{name}}</h3><p style="${BODY}font-size:.83rem;line-height:1.5;color:var(--color-text-muted);">{{description}}</p><strong style="${HEADING}font-size:1.05rem;color:var(--color-primary-on-surface);">{{price}}</strong>`
      : `<span style="${ACCENT}font-size:1.1rem;color:var(--color-primary-on-surface);">★ {{rating}}</span><p style="${BODY}font-size:.88rem;line-height:1.65;color:var(--color-text);">“{{text}}”</p><strong style="${BODY}font-size:.82rem;color:var(--color-text-muted);">{{name}}</strong>`;
    return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,230px),1fr));gap:14px;">{{#items}}<article style="padding:${layout === 1 ? "20px 14px" : "20px"};border-radius:${layout === 2 ? "4px 18px 4px 18px" : "14px"};background:${layout === 1 ? "var(--color-primary)" : "var(--color-surface)"};color:${layout === 1 ? "var(--color-on-primary)" : "var(--color-text)"};">${itemContent}</article>{{/items}}</div>`;
  }
  if (type === "gallery" || type === "team") {
    const collection = type === "gallery" ? "images" : "members";
    const title = type === "gallery" ? "{{caption}}" : "{{name}}";
    const subtitle = type === "team" ? `<p style="${BODY}font-size:.78rem;line-height:1.5;color:var(--color-text-muted);margin:4px 0 0;">{{role}}</p>` : "";
    return layout === 1
      ? `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,140px),1fr));gap:10px;">{{#${collection}}}<figure style="margin:0;position:relative;overflow:hidden;border-radius:${layout === 1 ? "12px" : "40% 40% 12px 12px"};"><img src="{{image}}" alt="${title}" style="display:block;width:100%;height:auto;aspect-ratio:3/4;object-fit:cover;"/><figcaption style="position:absolute;inset:auto 0 0;padding:28px 10px 10px;background:linear-gradient(transparent,var(--color-primary));color:var(--color-on-primary);${BODY}font-size:.8rem;font-weight:700;">${title}</figcaption></figure>{{/${collection}}}</div>`
      : `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,190px),1fr));gap:14px;">{{#${collection}}}<article style="overflow:hidden;border-radius:${layout === 2 ? "50% 50% 12px 12px" : "12px"};background:var(--color-surface);"><img src="{{image}}" alt="${title}" style="display:block;width:100%;height:auto;aspect-ratio:${layout === 2 ? "1/1" : "4/3"};object-fit:cover;"/><div style="padding:12px;"><h3 style="${HEADING}font-size:.9rem;color:var(--color-text);margin:0;">${title}</h3>${subtitle}</div></article>{{/${collection}}}</div>`;
  }
  if (type === "marquee") return `<div style="display:flex;flex-wrap:wrap;justify-content:center;gap:8px;">{{#items}}<span style="display:inline-flex;align-items:center;min-height:40px;padding:0 18px;border-radius:${layout === 0 ? "999px" : layout === 1 ? "6px" : "999px 999px 6px 999px"};background:${layout === 1 ? "var(--color-primary)" : "var(--color-surface)"};color:${layout === 1 ? "var(--color-on-primary)" : "var(--color-primary-on-surface)"};${BODY}font-size:.78rem;font-weight:700;">{{text}}</span>{{/items}}</div>`;
  if (type === "newsletter") return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:22px;align-items:center;padding:${layout === 2 ? "26px 18px" : "30px"};border-radius:${layout === 1 ? "8px" : "16px"};background:var(--color-surface);"><div><span style="${ACCENT}font-size:1rem;color:var(--color-primary-on-surface);">Nourivelle Notes</span><h2 style="${HEADING}font-size:1.65rem;line-height:1.15;color:var(--color-text);margin:8px 0;">{{title}}</h2><p style="${BODY}font-size:.88rem;line-height:1.6;color:var(--color-text-muted);">{{subtitle}}</p></div><div style="display:flex;flex-wrap:wrap;gap:8px;"><input aria-label="Alamat email" placeholder="Alamat email kamu" style="flex:1;min-width:min(100%,190px);min-height:46px;padding:0 14px;border:1px solid var(--color-border);border-radius:999px;background:var(--color-background);color:var(--color-text);font-size:16px;"/><a href="{{button_link}}" style="display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:0 18px;border-radius:999px;background:var(--color-primary);color:var(--color-on-primary);${BODY}font-size:.84rem;font-weight:700;text-decoration:none;">{{button_text}}</a></div></div>`;
  if (type === "divider") return `<div style="display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:14px;padding:${layout === 1 ? "24px 0" : "10px 0"};"><span style="height:${layout === 2 ? "4px" : "1px"};background:var(--color-secondary);border-radius:4px;"></span><span style="${ACCENT}font-size:${layout === 1 ? "1.2rem" : ".95rem"};color:var(--color-primary-on-background);">{{label}}</span><span style="height:1px;background:var(--color-border);"></span></div>`;
  if (type === "about") return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:${layout === 2 ? "14px" : "28px"};align-items:center;"><img src="{{image}}" alt="Nourivelle wellness" style="display:block;width:100%;height:auto;aspect-ratio:${layout === 1 ? "16/9" : "4/3"};object-fit:cover;border-radius:${layout === 2 ? "50% 50% 12px 12px" : "16px"};"/><div style="padding:${layout === 2 ? "20px" : "0"};"><span style="${ACCENT}font-size:1rem;color:var(--color-primary-on-background);">Kisah Nourivelle</span><h2 style="${HEADING}font-size:clamp(1.55rem,3vw,2.25rem);line-height:1.15;color:var(--color-text);">{{title}}</h2><p style="${BODY}font-size:.92rem;line-height:1.7;color:var(--color-text-muted);">{{content}}</p><a href="{{cta_link}}" style="display:inline-flex;align-items:center;min-height:44px;padding:0 16px;border-radius:999px;background:var(--color-primary);color:var(--color-on-primary);${BODY}font-size:.84rem;font-weight:700;text-decoration:none;">{{cta_text}}</a></div></div>`;
  if (type === "hero") return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:${layout === 1 ? "12px" : "28px"};align-items:center;"><div style="padding:${layout === 2 ? "26px" : "8px 0"};border-radius:${layout === 2 ? "16px" : "0"};background:${layout === 2 ? "var(--color-surface)" : "transparent"};"><span style="display:inline-flex;align-items:center;min-height:30px;padding:0 12px;border-radius:999px;background:var(--color-surface);color:var(--color-primary-on-surface);${BODY}font-size:.72rem;font-weight:700;">{{badge}}</span><h1 style="${HEADING}font-size:clamp(2rem,5vw,3.55rem);line-height:1.04;color:var(--color-text);margin:14px 0 12px;">{{headline}}</h1><p style="${BODY}font-size:.98rem;line-height:1.65;color:var(--color-text-muted);max-width:35rem;">{{subheadline}}</p><a href="{{cta_link}}" style="display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:0 20px;border-radius:${layout === 2 ? "8px" : "999px"};background:var(--color-primary);color:var(--color-on-primary);${BODY}font-size:.86rem;font-weight:700;text-decoration:none;">{{cta_text}}</a></div><img src="{{image}}" alt="Rutinitas wellness Nourivelle" style="display:block;width:100%;max-width:100%;height:auto;aspect-ratio:${layout === 1 ? "16/8" : "1.25/1"};object-fit:cover;border-radius:${layout === 2 ? "50% 50% 12px 12px" : "16px"};"/></div>`;
  if (type === "contact") return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:20px;align-items:center;padding:${layout === 1 ? "24px" : "0"};border-radius:16px;background:${layout === 1 ? "var(--color-surface)" : "transparent"};"><div><span style="${ACCENT}color:var(--color-primary-on-background);font-size:1rem;">Kami siap membantu</span><h2 style="${HEADING}font-size:1.8rem;color:var(--color-text);margin:8px 0;">{{title}}</h2><p style="${BODY}font-size:.9rem;line-height:1.6;color:var(--color-text-muted);">{{subtitle}}</p></div><div style="padding:18px;border-left:${layout === 2 ? "4px solid var(--color-secondary)" : "1px solid var(--color-border)"};${BODY}font-size:.88rem;line-height:1.9;color:var(--color-text);">{{phone}}<br/>{{email}}<br/>{{address}}</div><a href="{{cta_link}}" style="display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 18px;border-radius:999px;background:var(--color-primary);color:var(--color-on-primary);${BODY}font-weight:700;text-decoration:none;">{{cta_text}}</a></div>`;
  if (type === "location") return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:18px;align-items:stretch;"><div style="padding:22px;border-radius:${layout === 1 ? "50% 50% 12px 12px" : "14px"};background:var(--color-primary);color:var(--color-on-primary);"><span style="${BODY}font-size:.72rem;text-transform:uppercase;">Nourivelle Studio</span><h2 style="${HEADING}font-size:1.55rem;margin:9px 0;">{{title}}</h2><p style="${BODY}font-size:.88rem;line-height:1.7;">{{address}}<br/>{{hours}}</p></div><div style="padding:22px;border:${layout === 2 ? "0" : "1px solid var(--color-border)"};border-radius:14px;background:var(--color-surface);"><span style="${ACCENT}font-size:1rem;color:var(--color-primary-on-surface);">Mampir kapan saja</span><p style="${BODY}font-size:.9rem;line-height:1.7;color:var(--color-text-muted);">{{note}}</p></div></div>`;
  if (type === "newsletter") return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:22px;align-items:center;padding:${layout === 2 ? "26px 18px" : "30px"};border-radius:${layout === 1 ? "8px" : "16px"};background:var(--color-surface);"><div><span style="${ACCENT}font-size:1rem;color:var(--color-primary-on-surface);">Nourivelle Notes</span><h2 style="${HEADING}font-size:1.65rem;line-height:1.15;color:var(--color-text);margin:8px 0;">{{title}}</h2><p style="${BODY}font-size:.88rem;line-height:1.6;color:var(--color-text-muted);">{{subtitle}}</p></div><div style="display:flex;flex-wrap:wrap;gap:8px;"><input aria-label="Alamat email" placeholder="Alamat email kamu" style="flex:1;min-width:min(100%,190px);min-height:46px;padding:0 14px;border:1px solid var(--color-border);border-radius:999px;background:var(--color-background);color:var(--color-text);font-size:16px;"/><a href="{{button_link}}" style="display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:0 18px;border-radius:999px;background:var(--color-primary);color:var(--color-on-primary);${BODY}font-size:.84rem;font-weight:700;text-decoration:none;">{{button_text}}</a></div></div>`;
  if (type === "video") return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:22px;align-items:center;"><a href="{{video_url}}" style="position:relative;display:block;overflow:hidden;border-radius:${layout === 1 ? "50% 50% 12px 12px" : "16px"};"><img src="{{image}}" alt="Cerita wellness Nourivelle" style="display:block;width:100%;height:auto;aspect-ratio:16/10;object-fit:cover;"/><span style="position:absolute;inset:50% auto auto 50%;transform:translate(-50%,-50%);display:grid;place-items:center;width:54px;height:54px;border-radius:50%;background:var(--color-primary);color:var(--color-on-primary);">▶</span></a><div><span style="${ACCENT}color:var(--color-primary-on-background);">Cerita di balik ritual</span><h2 style="${HEADING}font-size:1.7rem;color:var(--color-text);">{{title}}</h2><p style="${BODY}font-size:.9rem;line-height:1.65;color:var(--color-text-muted);">{{subtitle}}</p></div></div>`;
  if (type === "cta") return `<div style="display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:18px;padding:${layout === 1 ? "28px" : "24px"};border-radius:${layout === 2 ? "50px 12px 50px 12px" : "14px"};background:var(--color-primary);color:var(--color-on-primary);"><div><span style="${ACCENT}font-size:1rem;color:var(--color-accent-on-primary);">Satu langkah kecil</span><h2 style="${HEADING}font-size:1.55rem;margin:6px 0;">{{title}}</h2><p style="${BODY}font-size:.88rem;line-height:1.5;margin:0;">{{text}}</p></div><a href="{{cta_link}}" style="display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:0 19px;border-radius:999px;background:var(--color-accent);color:var(--color-on-accent);${BODY}font-weight:700;text-decoration:none;">{{cta_text}}</a></div>`;
  return `<div style="max-width:780px;margin:0 auto;text-align:center;padding:${layout === 1 ? "24px 0" : "12px"};"><span style="${ACCENT}font-size:${layout === 2 ? "1.35rem" : "1rem"};color:var(--color-primary-on-background);">{{label}}</span><span style="display:block;width:${layout === 1 ? "72px" : "42px"};height:2px;margin:12px auto;background:var(--color-secondary);"></span></div>`;
}

function makeVariant(type: string, sectionName: string, variantName: string, slug: string, layout: number) {
  const config = SECTION_CONFIGS[type];
  const id = vid(`${type}-${slug}`);
  return {
    id,
    name: variantName,
    description: `Komposisi ${variantName.toLowerCase()} untuk section ${sectionName.toLowerCase()} Nourivelle.`,
    layout: id,
    configFields: inferFields(config),
    defaultConfig: { ...config },
    mockup: `${type.replace("_", "-")}-nourivelle-${layout + 1}`,
    html: `<section data-tpl-type="${type}" data-tpl-variant="${id}" style="padding:32px 18px;background:${layout === 1 ? "var(--color-surface)" : "var(--color-background)"};"><div style="max-width:1152px;margin:0 auto;">${["hero", "divider", "marquee", "about", "contact", "location", "newsletter", "video", "cta"].includes(type) ? "" : heading()}${renderBody(type, layout)}</div></section>`,
  };
}

function renderBody(type: string, layout: number): string {
  if (["product_grid", "features", "steps", "menu_board", "testimonials", "faq", "pricing", "gallery", "team", "marquee", "divider"].includes(type)) return itemList(type, layout);
  return itemList(type, layout);
}

const VARIANT_NAMES = [
  ["feature-cards", "Ritual Cards"],
  ["editorial-stack", "Editorial Stack"],
  ["soft-arc", "Soft Arc"],
] as const;

const PREVIEW_ORDER = [
  "hero", "menu_board", "product_grid", "about", "features", "pricing", "team", "marquee", "gallery", "testimonials", "newsletter", "steps", "location", "faq", "contact", "video", "cta", "divider",
];

export const SECTIONS: SectionTypeDefinition[] = [...TYPES]
  .sort(([left], [right]) => PREVIEW_ORDER.indexOf(left) - PREVIEW_ORDER.indexOf(right))
  .map(([type, name, icon]) => ({
  type,
  name,
  icon,
  variants: VARIANT_NAMES.map(([slug, label], layout) => makeVariant(type, name, label, `${slug}-${layout + 1}`, layout)),
  }));

export function sectionVariant(type: string, layout = 0): string {
  const spec = SECTIONS.find((section) => section.type === type);
  return spec?.variants[layout]?.id ?? spec?.variants[0]?.id ?? vid(`${type}-feature-cards-1`);
}