import type { ColorScheme } from "../../color-schemes";

export const COLOR_SCHEMES: ColorScheme[] = [
    // Light schemes (10)
    {
      id: 'terracotta-classic',
      name: 'Terracotta Classic',
      category: 'light',
      palette: { background: '#fffbeb', surface: '#fef3c7', primary: '#c2410c', accent: '#f59e0b', text: '#1c1917', textMuted: '#57534e', border: '#fde68a' },
      headingFont: 'Poppins',
      bodyFont: 'Inter',
    },
    {
      id: 'rust-warmth',
      name: 'Rust Warmth',
      category: 'light',
      palette: { background: '#fefaf0', surface: '#fefce8', primary: '#b45309', accent: '#fbbf24', text: '#1c1917', textMuted: '#57534e', border: '#fde68a' },
      headingFont: 'Playfair Display',
      bodyFont: 'Inter',
    },
    {
      id: 'amber-glow',
      name: 'Amber Glow',
      category: 'light',
      palette: { background: '#fffbeb', surface: '#fef3c7', primary: '#d97706', accent: '#fcd34d', text: '#1c1917', textMuted: '#57534e', border: '#fde68a' },
      headingFont: 'Cormorant Garamond',
      bodyFont: 'Inter',
    },
    {
      id: 'clay-pottery',
      name: 'Clay Pottery',
      category: 'light',
      palette: { background: '#fdfdf8', surface: '#fef9e7', primary: '#a16207', accent: '#fde68a', text: '#1c1917', textMuted: '#57534e', border: '#e4d5b7' },
      headingFont: 'Montserrat',
      bodyFont: 'Lato',
    },
    {
      id: 'sunset-kitchen',
      name: 'Sunset Kitchen',
      category: 'light',
      palette: { background: '#fff7ed', surface: '#fed7aa', primary: '#ea580c', accent: '#fb923c', text: '#431407', textMuted: '#57534e', border: '#fec99a' },
      headingFont: 'Syne',
      bodyFont: 'Inter',
    },
    {
      id: 'spice-market',
      name: 'Spice Market',
      category: 'light',
      palette: { background: '#fdf8f3', surface: '#fef3c7', primary: '#9a3412', accent: '#f59e0b', text: '#1c1917', textMuted: '#57534e', border: '#fde68a' },
      headingFont: 'Bebas Neue',
      bodyFont: 'Inter',
    },
    {
      id: 'harvest-gold',
      name: 'Harvest Gold',
      category: 'light',
      palette: { background: '#fefce8', surface: '#fef9c3', primary: '#854d0e', accent: '#eab308', text: '#1c1917', textMuted: '#57534e', border: '#fde047' },
      headingFont: 'Raleway',
      bodyFont: 'Inter',
    },
    {
      id: 'cream-soup',
      name: 'Cream Soup',
      category: 'light',
      palette: { background: '#fafaf9', surface: '#f5f5f4', primary: '#78716c', accent: '#a3e635', text: '#1c1917', textMuted: '#57534e', border: '#e7e5e4' },
      headingFont: 'DM Serif Display',
      bodyFont: 'Inter',
    },
    {
      id: 'ginger-zest',
      name: 'Ginger Zest',
      category: 'light',
      palette: { background: '#fffbeb', surface: '#fef3c7', primary: '#92400e', accent: '#fbbf24', text: '#1c1917', textMuted: '#57534e', border: '#fde68a' },
      headingFont: 'Outfit',
      bodyFont: 'Inter',
    },
    {
      id: 'paprika-rich',
      name: 'Paprika Rich',
      category: 'light',
      palette: { background: '#fef2f2', surface: '#fee2e2', primary: '#7c2d12', accent: '#f97316', text: '#450a0a', textMuted: '#7f1d1d', border: '#fecaca' },
      headingFont: 'Plus Jakarta Sans',
      bodyFont: 'Inter',
    },
    // Dark schemes (10)
    {
      id: 'ember-hearth',
      name: 'Ember Hearth',
      category: 'dark',
      palette: { background: '#1c1917', surface: '#292524', primary: '#fb923c', accent: '#fbbf24', text: '#fafaf9', textMuted: '#a8a29e', border: '#44403c' },
      headingFont: 'Playfair Display',
      bodyFont: 'Inter',
    },
    {
      id: 'charcoal-grill',
      name: 'Charcoal Grill',
      category: 'dark',
      palette: { background: '#0c0a09', surface: '#1c1917', primary: '#f97316', accent: '#fde047', text: '#fafaf9', textMuted: '#a8a29e', border: '#44403c' },
      headingFont: 'Syne',
      bodyFont: 'Inter',
    },
    {
      id: 'midnight-feast',
      name: 'Midnight Feast',
      category: 'dark',
      palette: { background: '#141210', surface: '#1f1d1a', primary: '#f59e0b', accent: '#fcd34d', text: '#fefce8', textMuted: '#a8a29e', border: '#44403c' },
      headingFont: 'Cormorant Garamond',
      bodyFont: 'Inter',
    },
    {
      id: 'copper-pot',
      name: 'Copper Pot',
      category: 'dark',
      palette: { background: '#0f0e0d', surface: '#1c1917', primary: '#ea580c', accent: '#fbbf24', text: '#fafaf9', textMuted: '#a8a29e', border: '#44403c' },
      headingFont: 'Montserrat',
      bodyFont: 'Lato',
    },
    {
      id: 'bronze-kitchen',
      name: 'Bronze Kitchen',
      category: 'dark',
      palette: { background: '#11100d', surface: '#1c1917', primary: '#d97706', accent: '#fde047', text: '#fefce8', textMuted: '#a8a29e', border: '#44403c' },
      headingFont: 'Raleway',
      bodyFont: 'Inter',
    },
    {
      id: 'obsidian-broth',
      name: 'Obsidian Broth',
      category: 'dark',
      palette: { background: '#080706', surface: '#141210', primary: '#fbbf24', accent: '#fde68a', text: '#fefce8', textMuted: '#a8a29e', border: '#292524' },
      headingFont: 'Bebas Neue',
      bodyFont: 'Inter',
    },
    {
      id: 'smoked-paprika',
      name: 'Smoked Paprika',
      category: 'dark',
      palette: { background: '#0d0b09', surface: '#1c1917', primary: '#c2410c', accent: '#fde68a', text: '#fafaf9', textMuted: '#a8a29e', border: '#44403c' },
      headingFont: 'DM Serif Display',
      bodyFont: 'Inter',
    },
    {
      id: 'cinder-oven',
      name: 'Cinder Oven',
      category: 'dark',
      palette: { background: '#0a0908', surface: '#181614', primary: '#9a3412', accent: '#fcd34d', text: '#fafaf9', textMuted: '#a8a29e', border: '#44403c' },
      headingFont: 'Outfit',
      bodyFont: 'Inter',
    },
    {
      id: 'volcanic-ash',
      name: 'Volcanic Ash',
      category: 'dark',
      palette: { background: '#0f0e0d', surface: '#1c1917', primary: '#78716c', accent: '#eab308', text: '#fafaf9', textMuted: '#a8a29e', border: '#44403c' },
      headingFont: 'Plus Jakarta Sans',
      bodyFont: 'Inter',
    },
    {
      id: 'coal-ember',
      name: 'Coal Ember',
      category: 'dark',
      palette: { background: '#090807', surface: '#141210', primary: '#57534e', accent: '#fde047', text: '#fafaf9', textMuted: '#a8a29e', border: '#292524' },
      headingFont: 'Space Grotesk',
      bodyFont: 'Inter',
    },
];
